(function() {var implementors = {};
implementors["lcov_merge"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='lcov_merge/file/struct.File.html' title='lcov_merge::file::File'>File</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='lcov_merge/file/struct.Files.html' title='lcov_merge::file::Files'>Files</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='lcov_merge/branch/struct.BranchUnit.html' title='lcov_merge::branch::BranchUnit'>BranchUnit</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='lcov_merge/branch/struct.Branch.html' title='lcov_merge::branch::Branch'>Branch</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='lcov_merge/branch/struct.BranchBlocks.html' title='lcov_merge::branch::BranchBlocks'>BranchBlocks</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='lcov_merge/branch/struct.Branches.html' title='lcov_merge::branch::Branches'>Branches</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='lcov_merge/line/struct.Line.html' title='lcov_merge::line::Line'>Line</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='lcov_merge/line/struct.Lines.html' title='lcov_merge::line::Lines'>Lines</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='lcov_merge/function/struct.Functions.html' title='lcov_merge::function::Functions'>Functions</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='lcov_merge/function/struct.Function.html' title='lcov_merge::function::Function'>Function</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='lcov_merge/test/struct.Test.html' title='lcov_merge::test::Test'>Test</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='lcov_merge/test/struct.Tests.html' title='lcov_merge::test::Tests'>Tests</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
